%define upstream_name    Test-Pod-Content
%define upstream_version 0.0.6

Name:       perl-%{upstream_name}
Version:    %perl_convert_version %{upstream_version}
Release:    3

Summary:    Test a Pod's content
License:    GPL+ or Artistic
Group:      Development/Perl
Url:        http://search.cpan.org/dist/%{upstream_name}
Source0:    http://www.cpan.org/modules/by-module/Test/Test-Pod-Content-v%{upstream_version}.tar.gz

BuildRequires: perl(Pod::Simple)
BuildRequires: perl(Test::More)
BuildRequires: perl(version)
BuildRequires: perl(Module::Build::Compat)
BuildArch: noarch

%description
This is a very simple module for testing a Pod's content. It is mainly
intended for testing the content of generated Pod - that is, the Pod
included in perl modules generated by some mechanism.

Another usage example is to test whether all files contain the same
copyright notice:

 plan tests => scalar @filelist;

%prep
%setup -q -n %{upstream_name}-v%{upstream_version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor

%make

%check
%make test

%install
rm -rf %buildroot
%makeinstall_std

%clean
rm -rf %buildroot

%files
%defattr(-,root,root)
%doc META.yml Changes README
%{_mandir}/man3/*
%perl_vendorlib/*




%changelog
* Sat Apr 16 2011 Funda Wang <fwang@mandriva.org> 0.0.5-2mdv2011.0
+ Revision: 653622
- rebuild for updated spec-helper

* Wed Aug 25 2010 Jérôme Quelin <jquelin@mandriva.org> 0.0.5-1mdv2011.0
+ Revision: 573091
- import perl-Test-Pod-Content

